version: '3.2'
services:
  vw-bcp:
    image: vaultwarden_dropbox_backup:latest
    restart: always
    volumes:
      - ../vw-data/db.sqlite3:/db.sqlite3
      - ./dropbox_uploader.conf:/root/.dropbox_uploader
    environment:
      - BACKUP_ENCRYPTION_KEY=xxx
      #- DELETE_AFTER=10
